---

- name: Remove Raft and Serf
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ data_dir }}/raft"
    - "{{ data_dir }}/serf"

- name: Restart the Consul service
  service:
    name: consul
    state: restarted
    enabled: yes