---
server: "false"


log_level: "DEBUG"
enable_syslog: "true"

data_dir: "/etc/consul.d/"

bind_addr: "0.0.0.0"
client_addr: "0.0.0.0"

verify_incoming_rpc: "true"
verify_incoming_https: "false"
verify_incoming: "false"
verify_outgoing: "true"
verify_server_hostname: "false"

ca_file_certificate: "ca.pem"
client_file_key: "client.key"
client_file_certificate: "client.pem"

cert_path: "/consul/data/certificates/ssl"
tmp_path_certificates: "consul/data/certificates/ssl"
path_certificate: "/etc/consul.d/certificates/ssl"

ca_file: "{{ path_certificate }}/ca.pem"
cert_file: "{{ path_certificate }}/client.pem"
key_file: "{{ path_certificate }}/client.key"

enable_script_checks: "false"
disable_remote_exec: "true"