---
device: "/dev/sdb"
dev_size: "90g"
vg_name: "consul"
lv_name: "data"
logical_device: "/dev/consul/data"
dir_mount:
  - "/consul"
  - "/consul/data"
path_mount: "/consul/data"


# pvcreate /dev/sdb
# vgcreate data /dev/sdb
# lvcreate -n ibm -L 25G data
# mkfs.ext4 /dev/data/ibm
# mkdir /ibm
# mount /dev/data/ibm /ibm/